### ISSUE TITLE
ARC version?

### ISSUE THREAD

**Issue by ryanmsusa** [jasarien/JSTokenField#27]
I tried to convert to arc by removing the release statements and dealloc functions but using the instruments "leaks" program shows the live bytes continue to go up when pushing and popping a view controller that contains jstokenfield.

Any chance you can convert to ARC or give tips on how I can?

**Comment by jasarien** [comment]
I don't use ARC myself, so I have no immediate plans to support an ARC version. The only advice I can give is that as well as removing reference counting methods, ensure that your project is set to compile using ARC. You can look through the many forks of this project to see if someone has already converted to ARC. I'd be surprised if someone hasn't already done it.

**Comment by jasarien** [comment]
Here is a fork with an ARC conversion: https://github.com/FivesquareSoftware/JSTokenField
