### ISSUE TITLE
Button title is appearing beside the token

### ISSUE THREAD

**Issue by happy2share** [jasarien/JSTokenField#36]
The respective text is appending to button while adding the token. Please see the following screenshot
![screen shot 2014-07-08 at 12 48 54 pm](https://cloud.githubusercontent.com/assets/2097850/3506377/7cdcb030-0670-11e4-9258-d4ef1b1fe301.png)

Please help me out in removing the title beside the token.

**Comment by vvit** [comment]
I think this is not an issue? But feature :)
Try clearing the textfield in delegate's method:

``` objective-c
#pragma mark JSTokenFieldDelegate

- (void)tokenField:(JSTokenField *)tokenField didAddToken:(NSString *)title representedObject:(id)obj
{
    NSDictionary *recipient = [NSDictionary dictionaryWithObject:obj forKey:title];
    [_toRecipients addObject:recipient];
    tokenField.textField.text = @"";
}
```

**Comment by jasarien** [comment]
This is fixed in the latest head
