### ISSUE TITLE
Can't remove token on Ios 6

### ISSUE THREAD

**Issue by daida** [jasarien/JSTokenField#9]
Hi,

on iOs6 you can't select or remove a token.
It's works fine on iOs 5.

Daida

**Comment by siuying** [comment]
You may want to check my branch (https://github.com/siuying/JSTokenField/commits/siuying) on a fixes

**Comment by jasarien** [comment]
If you make a pull request, I'll be happy to merge it in.

**Comment by siuying** [comment]
@jasarien certainly. its mixed with a few other changes meanwhile, i will extract a PR.
